version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  myapp:
    build: .
    command: yarn start
    expose:
      - 8000
    depends_on:
      - db

  myapp-tests:
    build: .
    command: yarn test
    depends_on:
      - myapp